[project]
name = "mass-bike-routes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "googlemaps>=4.10.0",
    "more-itertools>=10.7.0",
    "playwright>=1.58.0",
    "requests>=2.32.4",
    "shot-scraper>=1.9.1",
]
